File inherits from Stream: proper support for print and println of al…
stm32duino/STM32SD pull request #72
Opened 2024-07-10 10:39 UTC by pschatzmann

**Summary**

File inherits from Stream: proper support for print and println of all supported data types.
The motivation for this, was that in all other SD libraries the File impelmentation is a subclass of Stream which itself is a subclass of Print.

With this change we can now also provide the files of this library to any Arduino function which expects a Stream or a Print.

**Validation**

I extended the test sketch Full.ino to test the readBytes() method and the printing of an integer.

**Closing issues**

I did not file any issue but decided to submit a pull request directly to speed up things.

2024-08-29 13:47 UTC, fpistm requested changes

2024-08-29 13:47 UTC, fpistm commented on src/STM32SD.h
> +
```suggestion

```

2024-09-05 09:11 UTC, fpistm approved these changes

2024-09-05 09:13 UTC, fpistm commented
Hi @pschatzmann 
I've updated your PR to remove useless `print`/`println` methods.
Thanks again for your contribution.

2024-09-05 09:17 UTC, pschatzmann commented
Cool, thanks

2024-09-05 09:26 UTC, merged